# Generated by Django 5.0.1 on 2024-01-20 16:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musiacians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='album_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('musician_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musiacians.musician_model')),
            ],
        ),
    ]
